next-hbbtv-brower: add to gthread-2.0 to LDFLAGS
It solves the following error when compiled with newer OE.
Source/WebKit/gtk/tests/Programs_unittests_testapplicationcache-testapplicationcache.o: undefined reference to symbol 'g_thread_init'

Also glib-2.0 was added in depends since gthread-2.0 is part of it.